//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BarberShopZiminDenis1116.EFDataBaseFolder
{
    using System;
    using System.Collections.Generic;
    
    public partial class Notes
    {
        public int idNote { get; set; }
        public int idFKService { get; set; }
        public int idFKClient { get; set; }
        public int idFKPersonal { get; set; }
        public string NateDate { get; set; }
        public string Comment { get; set; }
        public string DateStart { get; set; }
        public string DataFinish { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual Personal Personal { get; set; }
        public virtual Service Service { get; set; }
    }
}
